CREATE TABLE CALENDARMEMO (
CALENDARMEMO_CONTENTS VARCHAR(500),
CALENDARMEMO_YEAR INT,
CALENDARMEMO_MONTH INT,
CALENDARMEMO_DAY INT,
CALENDARMEMO_NUM INT,
CALENDARMEMO_ID VARCHAR(30),
CALENDARMEMO_PASSWD VARCHAR(30)
);

INSERT INTO CALENDARMEMO(CALENDARMEMO_CONTENTS, CALENDARMEMO_YEAR, CALENDARMEMO_MONTH, CALENDARMEMO_DAY)
VALUES ('test', 2011, 6, 1), ('test2', 2016, 5, 10);

select * from calendarmemo;